import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import api from '../api/axios';

function ResetPassword() {
  const { uid, token } = useParams(); const navigate = useNavigate();
  const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [done, setDone] = useState(false); const [loading, setLoading] = useState(false);
  const submit = async e => { e.preventDefault(); setError(''); if(password!==confirm){setError('Passwords do not match.');return;} setLoading(true); try { await api.post('/accounts/reset-password/',{uid,token,new_password:password}); setDone(true); setTimeout(()=>navigate('/login'),1200); } catch(e){setError(e.response?.data?.detail||'This reset link is invalid or expired.');} finally{setLoading(false);} };
  return <div className="auth-page"><div className="auth-side"><div className="brand light-brand"><span className="brand-mark">CP</span><span>CampusPulse</span></div><div><span className="eyebrow light">Secure recovery</span><h1>Choose a new password and continue.</h1><p>Use a strong password that you do not reuse elsewhere.</p></div><span className="auth-side-foot">Olabisi Onabanjo University</span></div><div className="auth-main"><div className="auth-card"><div className="auth-mobile-brand"><div className="brand"><span className="brand-mark">CP</span><span>CampusPulse</span></div></div><span className="eyebrow">New password</span><h2>Create a new password.</h2><p className="auth-sub">Your reset link is single-use.</p>{done?<div className="notice success">Password reset successfully. Redirecting to sign in…</div>:<form onSubmit={submit} className="stack-form"><label>New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required autoComplete="new-password"/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} required autoComplete="new-password"/></label><button className="button primary large" disabled={loading}>{loading?'Updating…':'Update password'}</button>{error&&<div className="notice error">{error}</div>}</form>}<p className="auth-switch"><Link to="/login">Back to sign in</Link></p></div></div></div>;
}
export default ResetPassword;
