# Generated by Django 5.2.13 on 2026-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesession',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
    ]
