# Generated by Django 5.2.13 on 2026-08-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ASSIGNMENT', 'Assignment'), ('VENUE_CHANGE', 'Venue Change')], default='GENERAL', max_length=15),
        ),
        migrations.AddField(
            model_name='announcement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
