# Generated by Django 5.2.13 on 2026-08-29 20:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_campusdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusdocument',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='campus_documents/'),
        ),
    ]
