# Generated by Django 5.2.17 on 2026-10-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_department'),
        ('attendance', '0010_alter_campusdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='campusdocument',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='classcode',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department'),
        ),
    ]
