# Generated by Django 5.2.13 on 2026-07-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
