# Generated by Django 5.2.13 on 2026-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_attendancepasskeygrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepasskeygrant',
            name='session_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
