# Generated by Django 5.2.13 on 2026-10-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_attendancepasskeygrant_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passkeychallenge',
            name='session_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
