# Generated by Django 5.2.17 on 2026-10-08 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lecturer_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('CLASS_REP', 'Class Representative'), ('LECTURER', 'Lecturer'), ('SUPER_ADMIN', 'Super Administrator')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='LecturerTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level')], max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department__name', 'level'],
                'unique_together': {('lecturer', 'department', 'level')},
            },
        ),
    ]
